### ISSUE TITLE
Mac OS WebApp

### ISSUE THREAD

**Issue by feed4rz** [revenkroz/telegram-web-app-bot-example#1]
Hi, sorry for a silly question, but how exactly did you pass the web_app link to a inlineKeyboard and menu_button?

<img width="632" alt="image" src="https://user-images.githubusercontent.com/13008534/164680415-157e535a-a794-4d09-8032-8bbd8a998007.png">

On iOS all of those buttons open Web App, but not on Mac OS. On Mac OS only thekeyboard button in the bottom works. It may be an issue with the url format, so can you please share the code from your bot? Thanks

**Comment by haidityara** [comment]
btw revenkroz already fix it but not update the script :(
